vector_version: "0.31.0-1"
vector_config:
  sources:
    metrics:
      type: host_metrics
      collectors: ["all"]
      filesystem.mountpoints: ["*"]
      disk.devices: ["*"] # optional, defaults to all to disk devices.
      network.devices: ["*"] # optional, defaults to all to network devices.
      scrape_interval_secs: 15 # optional, default, seconds
      namespace: "host" # optional, default
  transforms:
    parse_logs:
      inputs:
        - metrics
      source: |-
        . = parse_syslog!(string!(.message))
        .timestamp = to_string(.timestamp)
        .timestamp = slice!(.timestamp, start:0, end: -1)
      type: remap
  sinks:
    to_clickhouse:
      type: clickhouse
      inputs:
        - parse_logs
      database: logs
      endpoint: "http://localhost:8123"
      table: syslog
      compression: gzip
  api:
    enabled: true
    address: "0.0.0.0:8686"
